version: "3"
services:
  flask-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: iss_tracker
    container_name: ISSTracker_api
    restart: unless-stopped
    ports:
      - "5000:5000"
